[package]
name = "making_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json="0.9.0"
serde={version="1.0.172",features=["derive"]}
reqwest={version="0.10.0",features=["json"]}
tokio={version="0.2.3",features=["full"]}