//mod first_program;
//mod integer;
//mod mut_integer;
//mod str_string;
//mod string;
//mod tuple;
//mod funtion;
//mod ownership;
//mod ownershipin_function;
//mod owneship_func;
//mod slv_ownrship_us_tuple;
//mod slv_ownrsus_clone;
//mod slv_ownrsus_borrow;
//mod mut_borrow;
//mod borrow_rules;
//mod reference;
//mod daigling_reference;
//mod float_datatype;
//mod bool_datatype;
//mod char_datatype;
//mod array;
//mod arry_directly_pass;
//mod array_pass_by_referencr;
//mod read_array;
//mod read_array2;
//mod vector;
//mod vector_fun;
//mod inference;
//mod shadowing;
//mod if_else;
//mod while_loop;
//mod for_loop;
//mod match;
//mod user_input;
//mod struct_consept;
//mod struct_with_tuple;
//mod impl_in_struct;
//mod struct_show_by_default_value;
//mod enum_concept;
//mod enum_store_value;
//mod struct_use_inside_enum;
//mod impl_in_enum;
//mod constant;
//mod statics;
//mod generic_concept;
//mod generic_with_enum;
//mod generic_with_trait;
//mod trait_concept;
//mod trait_default_behaviour;
//mod trait_paramitrize;
//mod bound_trait;
//mod multi_trait;
//mod module;
//mod thread;
//mod multi_thread;
//mod chanal;
//mod multi_chanal;
//mod future_async_await;
//mod macros;
//mod macros_fun;
//mod closure;
//mod funtion_pointer;
//mod iterator;
//mod combinator;
//mod cmd_argument;
//mod hashmap;
mod  fetch_hashmap_value;
fn main() {
   // first_program::run();
   //integer::run();
   //mut_integer::run();
   //str_string::run();
   // string::run();
   //tuple::run();
   //funtion::run();
   //ownership::run();
   //ownershipin_function::run();
   //owneship_func::run();
   //slv_ownrsus_clone::run();
   //slv_ownrsus_borrow::run();
   //mut_borrow::run();
   //borrow_rules::run();
   //reference::run();
   //daigling_reference::run();
   //float_datatype::run();
   //bool_datatype::run();
   //char_datatype::run();
   //array::run();
   //arry_directly_pass::run();
   //array_pass_by_referencr::run();
   //read_array::run();
   //read_array2::run();
   //vector::run();
   //vector_fun::run();
   //inference::run();
   //shadowing::run();
   //if_else::run();
   //while_loop::run();
   //for_loop::run();
   //match::run();
   //user_input::run();
   //struct_consept::run();
   //enum_concept::run();
   //enum_store_value::run();
   //struct_use_inside_enum::run();
   //impl_in_enum::run();
   //struct_with_tuple::run();
   //impl_in_struct::run();
   //struct_show_by_default_value
   //constant::run();
   //statics::run();
   //generic_concept::run();
   //generic_with_enum::run();
   //generic_with_trait::run();
   // trait_concept::run();
   //trait_default_behaviour::run();
   //trait_paramitrize::run();
   //bound_trait::run();
   //multi_trait::run();
   //module::run();
   //thread::run();
   //multi_thread::run();
   //chanal::run();
   //multi_chanal::run();
   //future_async_await::run();
   //macros::run();
   //macros_fun::run();
   //closure::run();
   //funtion_pointer::run();
   //iterator::run();
   //combinator::run();
   //cmd_argument::run();
   //hashmap::run();
   fetch_hashmap_value::run();
}